### ISSUE TITLE
URLs contain backslashes on Windows

### ISSUE THREAD

**Issue by aloker** [canadaduane/snowpack-plugin-relative-css-urls#4]
Paths created by this plugin contain backslashes on Windows systems. This breaks the URLs in the browser.

I've submitted a PR to fix this (see #3)

**Comment by canadaduane** [comment]
I believe this is also related: https://gist.github.com/choksheak/d229ceae7b2a8bc7ae794ed30aabe150

**Comment by canadaduane** [comment]
Published as 1.1.1
